// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDMChannel(ctx context.Context, arg CreateDMChannelParams) (DmChannel, error)
	CreateUserDMChannel(ctx context.Context, arg CreateUserDMChannelParams) (UserDmChannel, error)
	GetDMChannelByChannelId(ctx context.Context, channelID uuid.UUID) (DmChannel, error)
	GetUserDMChannels(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
